global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
rule_files:
  - "alert_rules.yml" #mathematical expressions
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] #monitors prometheus server itself
  - job_name: "NGINX_SERVER"
    static_configs:
      - targets: ["<private-ip>:80"] #monitors nginx server
  - job_name: "Node_Exporter"
    static_configs:
      - targets: ["<private-ip>:9100"] #monitors node-exporter
  - job_name: "Prometheus-Nginx-Exporter"
    static_configs:
      - targets: ["<private-ip>:4040"] #monitors prometheus-nginx-exporter
